export const {
    NODE_ENV, MONGO_CONNECTION_STRING, PORT, ACCESS_TOKEN_SECRET, ACCESS_TOKEN_EXPIRY = '40d', SECRET_STRING, AWS_ACCESS_KEY, AWS_SECRET_KEY, S3_BUCKET, S3_IMAGE_URL,
} = process.env;

export const ORDER_STATUS = {
    PLACED: 1,
    SHIPPED: 2,
    DELIEVERED: 3,
    CANCELLED: 4,
};

export const ORDER_TYPE = {
    NORMAL: 1,
};
