export const {
    NODE_ENV, MONGO_CONNECTION_STRING, PORT, ACCESS_TOKEN_SECRET, ACCESS_TOKEN_EXPIRY = '40d', SECRET_STRING, AWS_ACCESS_KEY, AWS_SECRET_KEY, S3_BUCKET, S3_IMAGE_URL,
} = process.env;

export const ORDER_STATUS = {
    NEW_ORDER: 1,
    ACCEPTED: 2,
    IN_TRANSIT: 3,
    DELIEVERED: 4,
    CANCELLED: 5,
};

export const ORDER_TYPE = {
    NORMAL: 1,
};

export const USER_TYPE = {
    ADMIN: 1,
    DEALER: 2,
    CUSTOMER: 3,
};
